version: "2.4"

services:
  localstack:
    image: localstack/localstack:latest
    environment:
      DEBUG: ${DEBUG-}
      DOCKER_HOST: unix://var/run/docker.sock
    ports:
    - "127.0.0.1:4566:4566"            # LocalStack Gateway
    - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"

  envoy:
    image: envoyproxy/envoy:v1.23-latest
    ports:
    - "9901:9901"
    volumes:
    - ./.envoy/envoy.yaml:/etc/envoy/envoy.yaml
    volumes_from:
    - sds:ro
    depends_on:
      sds:
        condition: service_started

  sds:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      AWS_ENDPOINT: "http://localstack:4566"
      AWS_ACCESS_KEY_ID: doesnt
      AWS_SECRET_ACCESS_KEY: matter
    command:
    - "-debug"
